# control
---
- hosts: control
  become: true
  roles:
    - control

#  tasks: 
#    - name: install hooks
#      apt: name={{ item }} state=present update_cache=yes
#      with_items:
#        - curl
