---
# tasks file for lb01
- name: installing nginx       
  apt: name=nginx state=present update_cache=yes      

- name: ensuring nginx is started       
  service: name=nginx state=started enabled=yes      

- name: configure nginx site       
  template: src=/home/vagrant/ansible/templates/nginx.conf.j2 dest=/etc/nginx/sites-available/myapp mode=0755       
  with_dict: "{{sites}}"
  notify: restart nginx      

- name: de-activate default nginx site       
  file: path=/etc/nginx/sites-enabled/default state=absent       
  notify: restart nginx      

- name: activate demo nginx site       
  file: src=/etc/nginx/sites-available/myapp dest=/etc/nginx/sites-enabled/myapp state=link       
  with_dict: "{{sites}}"
  notify: restart nginx


